### PR TITLE
feat: add unity project

### PR DESCRIPTION
**Pull request by QuakeEye**
This pull request adds the unity project to the repository, and edits the gitignore to exclude unity Library folders etc.

### CODE REVIEW

**Review by joachimdekker — DISMISSED** [review]
lgtm

**Comment by Tboefijn** [comment]
Ik mis een project?!

**Comment by QuakeEye** [comment]
> lgtm

It really isn't you silly goose

**Review by joachimdekker — APPROVED** [review]
Nice "standard unity shit"

**Review by Tboefijn — APPROVED** [review]

**Pull request merged**
