### PR TITLE
bump: aplib.net 2.0

### PR DESCRIPTION
**Pull request by SilasPeters**
## Description

Much wow, much improve

## Testability

Run all tests

## Checklist
- [x] Set the proper pull request name
- [x] Merged main into your branch
- [x] ~Added a scene to the game for your changes~

### CODE REVIEW

**Review by joachimdekker — APPROVED** [review]
After careful consideration, and bruteforcing of the hash, I can conclude this is valid.

**Review by stickyPiston — APPROVED** [review]
頑張った！

**Comment by stickyPiston** [comment]
Silas made me do it

**Review by JoenvandeVorle — APPROVED** [review]
lgtm

**Pull request merged**
